[book]
title = "My own documentation on the rust language"
description = "Create book from markdown files. Like Gitbook but implemented in Rust"
authors = ["Oscar te Giffel"]
language = "en"

[rust]
edition = "2018"

[output.html]
mathjax-support = true
site-url = "/"
git-repository-url = "https://github.com/Oscarteg/rust-playground/tree/master/book"
edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"

[preprocessor.index]
index = true